### PR TITLE
Updated for newer Electron version + check for update on start

### PR DESCRIPTION
**Pull request by Vj3k0**
Some of used methods have been deprecated in newer version of Electron. Also, I've made it to update on start, since default time is 5 minutes to make initial check which I think is far too long (what about shorter app session?).

### CODE REVIEW

**Comment by justinmchase** [comment]
:+1: I'll test it out soon but this looks good. There is a work item to make the check interval configurable via a property in package.json.

**Comment by justinmchase** [comment]
Check interval:
https://github.com/EvolveLabs/electron-updater/issues/44

**Comment by michaeljcalkins** [comment]
@Vj3k0 @justinmchase If I can be of any assistance please let me know! :)

**Comment by kanekotic** [comment]
I think adding this changes are becoming part of the critical path, currently with versions of electron > 0.35 electron updater crashes.

**Pull request merged**
